logging-level: 10 # logging.DEBUG

ev3: False

# TODO: define values

uplink-cost: 0.1

simulation:
  active: False
  values:
    battery-level: 50
    avg-rtt: 50
    cpu-usage: 50
    memory-usage: 50
    used-ram: 1000
    available-ram: 1000
    disk-usage: 50
    traffic: 50

indicators:
  battery-level:
    poor:
      start: 0
      end: 35
    average:
      start: 36
      end: 75
    excellent:
      start: 76
      end: 100
  connectivity:
    poor:
      start: 0
      end: 35
    average:
      start: 36
      end: 75
    excellent:
      start: 76
      end: 100
  cpu-usage:
    excellent:
      start: 0
      end: 35
    average:
      start: 36
      end: 75
    poor:
      start: 76
      end: 100
  memory-usage:
    excellent:
      start: 0
      end: 35
    average:
      start: 36
      end: 75
    poor:
      start: 76
      end: 100
  transmission-cost:
    excellent:
      start: 0
      end: 35
    average:
      start: 36
      end: 75
    poor:
      start: 76
      end: 100