logging-level: 10 # logging.DEBUG

# TODO: reward model must be defined in more detail (could be done by operator)
reward-modes:
  energy-aware:
    active: False
    ranges:
      - end: 0      # < 1 percent of battery needed
        reward: 5
      - start: 1    # 1 percent of battery needed
        end: 1
        reward: -1
      - start: 2    # >= 2 percent of battery needed
        reward: -1
  time-aware:
    active: True
    ranges:
      - start: 0
        end: 0.5
        reward: 4
      - start: 0.6
        end: 1.5
        reward: 2
      - start: 1.6
        end: 2
        reward: 1
      - start: 2.5
        reward: -5
  traffic-aware:
    active: False

basic-reward: 1

ev3: False