logging-level: 10 # logging.DEBUG

hyper-parameters:
  batch-size: 64
  gamma: 0.999        # discount factor used in the Bellman equation
  eps-start: 1        # starting value of epsilon (epsilon = exploration rate)
  eps-end: 0.01       # ending value of epsilon
  eps-decay: 0.001    # decay rate used to decay epsilon over time
  target-update: 5    # defines how frequently (in terms of episodes), the target network weights are updated
  memory-size: 100000 # capacity of replay memory
  lr: 0.001           # learning rate
  num-episodes: 100   # number of episodes
  episode-length: 5   # number of smt problems solved in one episode

basic-reward: 1

reward-modes:
  energy-aware:
    active: False
    ranges:
      - end: 0      # < 1 percent of battery needed
        reward: 5
      - start: 1    # 1 percent of battery needed
        end: 1
        reward: -1
      - start: 2    # >= 2 percent of battery needed
        reward: -1
  time-aware:
    active: True
    ranges:
      - end: 2
        reward: 3
      - start: 2
        reward: -4
  traffic-aware:
    active: False

ev3: False

