decision-making:
  indicators:
    battery-level:
      offloading-threshold: 40
      locally-threshold: 95
      weight: 0.25
    connectivity:
      offloading-threshold: 1
      locally-threshold: 80
      weight: 0.25
    cpu-usage:
      offloading-threshold: 80
      locally-threshold: 5
      weight: 0.25
    memory-usage:
      offloading-threshold: 80
      locally-threshold: 5
      weight: 0.25
  offload-threshold: 0.5
  update-interval: 5 # how often a new decision value is calculated (in seconds)

logging-level: 10 # logging.DEBUG
api-url: http://10.0.0.13:5000/formulae

smt:
  watch-directory: /home/robot/develop/smt/watch  # in the following directory the SMT problems are added
  installation-location: "/home/robot/cvc4"

